"""Add auth and employee fields

Revision ID: 530bb92af894
Revises: 67b1c5b1ebef
Create Date: 2026-02-13 08:22:37.814132

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '530bb92af894'
down_revision = '67b1c5b1ebef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cita', schema=None) as batch_op:
        batch_op.add_column(sa.Column('empleado_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'usuario', ['empleado_id'], ['id'])

    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=128), nullable=True))
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.drop_column('password_hash')

    with op.batch_alter_table('cita', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('empleado_id')

    # ### end Alembic commands ###
