"""agregando relaciones

Revision ID: 67b1c5b1ebef
Revises: f8bffa88c912
Create Date: 2026-02-13 00:39:05.489313

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67b1c5b1ebef'
down_revision = 'f8bffa88c912'
branch_labels = None
depends_on = None


def upgrade():
    bind = op.get_bind()
    insp = sa.inspect(bind)
    if 'cita' not in insp.get_table_names():
        return
    cols = {c['name']: c for c in insp.get_columns('cita')}
    if 'cliente_id' not in cols or 'servicio_id' not in cols:
        return
    need = cols['cliente_id'].get('nullable', True) or cols['servicio_id'].get('nullable', True)
    if not need:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cita', schema=None) as batch_op:
        if cols['cliente_id'].get('nullable', True):
            batch_op.alter_column('cliente_id',
                   existing_type=sa.INTEGER(),
                   nullable=False)
        if cols['servicio_id'].get('nullable', True):
            batch_op.alter_column('servicio_id',
                   existing_type=sa.INTEGER(),
                   nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cita', schema=None) as batch_op:
        batch_op.alter_column('servicio_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('cliente_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
