"""empty message

Revision ID: 97bd2bf6f480
Revises: 530bb92af894
Create Date: 2026-02-13 21:05:14.623613

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97bd2bf6f480'
down_revision = '530bb92af894'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cita', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pagado', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('metodo_pago', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cita', schema=None) as batch_op:
        batch_op.drop_column('metodo_pago')
        batch_op.drop_column('pagado')

    # ### end Alembic commands ###
